<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

# 1 Subsetting: Indexing and Slicing

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

In [2]:
import numpy as np

In [3]:
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
np_array = np.array(py_list)

In [4]:
py_list[0]

'a1'

In [5]:
py_list[-1]

'j10'

In [7]:
py_list[0:3]

['a1', 'b2', 'c3']

In [ ]:
py_list[1:6:2] #gives index 1 to 5 in steps of 2

['b2', 'd4', 'f6']

In [9]:
py_list[5:]

['f6', 'g7', 'h8', 'i9', 'j10']

In [10]:
py_list[:5]

['a1', 'b2', 'c3', 'd4', 'e5']

In [12]:
py_list[5:2:-1] #gives index 5 to 3 in reverse

['f6', 'e5', 'd4']

In [14]:
py_list[::-1] #reverses the entire list

['j10', 'i9', 'h8', 'g7', 'f6', 'e5', 'd4', 'c3', 'b2', 'a1']

## 1.2 Arrays only | Subsetting by masking

In [15]:
np_array = np.array([1,2,3,4,5,6,7,8,9,10])
my_mask = np_array > 3
my_mask

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [16]:
np_array[my_mask]
#show only those that are true, only works for numpy

array([ 4,  5,  6,  7,  8,  9, 10])

In [18]:
np_array[np_array > 3]
#same thing but without going through the variable

array([ 4,  5,  6,  7,  8,  9, 10])

In [20]:
np_array[~(np_array > 3)]
# '~' means not

array([1, 2, 3])

In [21]:
np_array[(np_array > 3) & (np_array < 8)]

array([4, 5, 6, 7])

In [23]:
np_array[(np_array < 3) | (np_array > 8)]

array([ 1,  2,  9, 10])

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [24]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

In [25]:
py_list_2d[3]

[4, 'D']

In [26]:
np_array_2d[3]

array(['4', 'D'], dtype='<U21')

In [27]:
py_list_2d[3][0]

4

In [ ]:
np_array_2d[3,0]

np.str_('4')

In [30]:
py_list_2d[:3]

[[1, 'A'], [2, 'B'], [3, 'C']]

In [32]:
np_array_2d[:3]

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C']], dtype='<U21')

In [ ]:
py_list_2d[:3][0]
#slices [:3] first, then [0]

[1, 'A']

In [34]:
np_array_2d[:3, 0]

array(['1', '2', '3'], dtype='<U21')

In [35]:
py_list_2d[3:6][0]

[4, 'D']

In [36]:
np_array_2d[3:6, 0]

array(['4', '5', '6'], dtype='<U21')

In [37]:
np_array_2d[:, 0]

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U21')

## 1.4 Growing lists

In [40]:
x=[1,2]*5
x

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [42]:
x = [1]
x = x + [2]
x = x + [3]
x = x + [4]
x

[1, 2, 3, 4]

In [43]:
x = [1]
x += [2]
x += [3]
x += [4]
x

[1, 2, 3, 4]

In [44]:
x = [1]
x.append(2)
x.append(3)
x.append(4)
x

[1, 2, 3, 4]

In [45]:
x = [1,2,3]
x += [4,5,6]
x

[1, 2, 3, 4, 5, 6]

In [47]:
x = [1,2,3]
x.extend([4,5,6])
x

[1, 2, 3, 4, 5, 6]

In [48]:
x = [1,2,3]
x.append([4,5,6])
x

[1, 2, 3, [4, 5, 6]]

# Some loose ends

## 1.5 Tuples

In [49]:
a = (1,2,3)

In [50]:
print(a[0])

1


In [51]:
a[0] = -1

TypeError: 'tuple' object does not support item assignment

## 1.6 Be VERY careful when copying

In [52]:
x = [1,2,3]
y = x
z = x
#if you do this, everytime you edit y or z, all x y and z will change
#ie, the lists are connected to the same "address"

In [53]:
x = [1,2,3]
y = x.copy()
z = x.copy()
#this ensures that the lists x, y and z are independent of each other
#ie, all the lists have different "addresses"

## Footnotes